name: "✨ Feature/enhancement request"
description: Propose something new.
title: "[Feature/Enhancement Request]: "
labels: ["feature request :sparkles:"]
body:
  - type: markdown
    attributes:
      value: |
        Please limit one request per issue.
  - type: textarea
    attributes:
      label: Feature/Enhancement Description
      placeholder: |
        What is the expected behavior of the proposed feature?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      placeholder: |
        Describe the solution you'd like in a clear and concise manner.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      placeholder: |
        Add any other context about the problem here.
    validations:
      required: false