name: Close Issues

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:

  close:
    name: Close Issue
    runs-on: ubuntu-latest
    steps:

      - name: Close Issue
        shell: bash
        run: |
          echo "${{github.event}}"