name: Push Test
on:
  push:

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest
    steps:

      - name: Event
        run: |
          gh api repos/YiiGuxing/Translation/releases --jq '.[]'