name: Push Test
on:
  push:

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest
    steps:

      - name: Event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/YiiGuxing/TranslationPlugin/releases --jq '.[]'