name: Push Test
on:
  push:

jobs:

    name: Push
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases --jq ".[] | select(.tag_name == \"v0.0.3\") | .id"