name: Push Test
on:
  push:
    branches:
      - main
      - 'rel/*'
      - 'act'

env:
  MY_ENV: env_test

jobs:

  push0:
    name: Push 0
    runs-on: ubuntu-latest
    outputs:
      k1: ${{ steps.e0.outputs.k1 }}
      k2: ${{ steps.e0.outputs.k2 }}
    steps:

      - name: Event 0
        id: e0
        run: |
          echo "k1=v1" >> $GITHUB_OUTPUT
          echo 'k2<<EOF' >> $GITHUB_OUTPUT
          echo "v2.0" >> $GITHUB_OUTPUT
          echo "v2.1" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          

      - name: Event 1
        run: |
          echo "k1: ${{ steps.e0.outputs.k1 }}"
          echo "k2: ${{ steps.e0.outputs.k2 }}"

  push1:
    name: Push 1
    needs: push0
    runs-on: ubuntu-latest
    steps:

      - name: Event
        run: |
          echo "k1: ${{ needs.push0.outputs.k1 }}"
          echo "k2: ${{ needs.push0.outputs.k2 }}"