name: Push Test
on:
  push:
    branches:
      - main
      - 'rel/*'

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"