name: Push Test
on:
  push:
    branches:
      - main
      - 'rel/*'

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest
    steps:

      - name: Event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{github.ref}}"
          echo "${{github.ref_name}}"