name: Release Test
on:
  release:
    types: [released]

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Delete Release
        if: github.event.release.target_commitish != 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ github.event.release.target_commitish }}"
          echo "${{ github.event.release.target_commitish != 'main' }}"
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.tag_name == "${{ github.event.release.tag_name }}") | .id' \
            | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}