name: Release Test
on:
  release:
    types: [released]

jobs:

  push:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Delete Release
        if: github.ref != 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq ".[] | select(.tag_name == \"${{ github.event.release.tag_name }}\") | .id" \
            | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}