# GitHub Actions Workflow created for handling the release process based on the draft release prepared
# with the Build workflow. Running the publishPlugin task requires the PUBLISH_TOKEN secret provided.

name: Tag Test
on:
  push:
    branches:
      - 'tag-*'
    tags:
      - 'v*'

jobs:

  release:
    name: Tag
    runs-on: ubuntu-latest
    steps:

      - name: Event
        run: |
          echo "${{github.event}}"